### ISSUE TITLE
lookUpBook Function

### ISSUE THREAD

**Issue by felix-murray** [felix-murray/cs1b#16]
# Logic

We need a function, `lookUpBook` to allow the user to search through the database for a specific book record.

Firstly, it should ask the user for the title of a book. This is the book that is to be  looked up in the inventory database. With this step, a search of both the `bookTitle` and `isbn` arrays is performed using the string find function.

 `strVar.find(str)` 

>Returns the index of the first occurrence of str in strVar. If str is not found, the special value string::npos is returned.

The function should search the `bookTitle` array for a title that matches the  one  entered  by  the  user.  If  no  match  is  found,  the  function  should display  a  message  indicating  that  the  book  is  not  in  inventory, and terminate. If the book is found, the function will show the title and ISBN of all records that match the search target and provide a method that allows them to select which one that want, then this function should call `bookInfo`, passing the correct data as arguments.

# Output Formatting

The `lookUpBook` search bar itself will look like this when the user first encounters it:

![Image of lookUpBook Search with Populated Search Field](https://i.gyazo.com/77b85dba37e8130193f0bb09315a7d93.png)

If the function finds a book based on the given search query, the user will see a screen similar to this for each matching book:

![Image of lookUpBook Finding a Book with the Given Search Term](https://i.gyazo.com/776c43cc3e2a17cc7c40813ca1686059.png)

  >**Note: Search queries will be displayed one item at a time, prompting the user each time if they would like to view the books record.**

Once the user selects "yes" to view a book, the `bookInfo` function will be called with the given parameters for the desired book

**Comment by jakehamilton** [comment]
Looks like this was moved back to finished a while ago. Are you still working on it?
